packages:
  - packages/eslint-plugin-oxygen-ui
  - packages/oxygen-ui
  - packages/oxygen-ui-icons-react
  - samples/oxygen-ui-test-app

ignoredBuiltDependencies:
  - '@swc/core'
  - nx

onlyBuiltDependencies:
  - esbuild

catalog:
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.1
  '@eslint/js': ^9.36.0
  '@mui/icons-material': ^7.3.4
  '@mui/material': ^7.3.4
  '@mui/x-charts': ^8.14.0
  '@mui/x-data-grid': ^8.16.0
  '@mui/x-date-pickers': ^8.17.0
  '@mui/x-tree-view': ^8.14.0
  '@types/eslint': ^9.6.1
  '@types/node': ^24.6.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@typescript-eslint/eslint-plugin': ^7.0.1
  '@typescript-eslint/parser': ^7.0.1
  '@vitejs/plugin-react-swc': ^4.2.0
  '@vitest/ui': ^4.0.7
  esbuild: ^0.25.12
  eslint: ^9.12.0
  eslint-plugin-react: ^7.33.2
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-react-refresh: ^0.4.24
  glob: ^11.0.3
  globals: ^16.4.0
  lucide-react: ^0.545.0
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  rimraf: ^6.1.0
  typescript: ^5.9.3
  typescript-eslint: ^8.45.0
  vite: ^7.2.1
  vitest: ^4.0.7
