packages:
  - packages/*
  - samples/*

catalog:
  '@emotion/react': 11.14.0
  '@emotion/styled': 11.14.1
  '@eslint/js': 9.39.0
  '@mui/icons-material': 7.3.4
  '@mui/material': 7.3.4
  '@mui/x-data-grid': 8.16.0
  '@mui/x-date-pickers': 8.16.0
  '@mui/x-tree-view': 8.14.0
  '@types/eslint': 9.6.1
  '@types/node': 24.6.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@typescript-eslint/eslint-plugin': 8.45.0
  '@typescript-eslint/parser': 8.45.0
  '@vitejs/plugin-react-swc': 4.2.0
  '@vitest/ui': 4.0.6
  esbuild: 0.25.11
  eslint: 9.12.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-react-refresh: 0.4.24
  glob: 11.0.3
  globals: 16.4.0
  lucide-react: 0.545.0
  prettier: 3.6.2
  react: 19.2.3
  react-dom: 19.2.3
  rimraf: 6.1.0
  typescript: 5.9.3
  typescript-eslint: 8.45.0
  vite: 7.1.12
  vitest: 4.0.6

ignoredBuiltDependencies:
  - '@swc/core'
  - nx

onlyBuiltDependencies:
  - esbuild
