/**
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { build } from "esbuild";
import { glob } from "glob";

// Build from dist (generated by build-icons.js)
const entryPoints = await glob("dist/**/*.ts");

await build({
  entryPoints,
  outdir: "dist",
  outExtension: { ".js": ".js" },
  bundle: false,
  splitting: false,
  sourcemap: true,
  format: "esm",
  target: ["esnext"],
  platform: "neutral",
  jsx: "automatic",
  logLevel: "info",
  loader: {
    ".css": "copy",
  },
});

// Build CommonJS version
await build({
  entryPoints: ["dist/index.ts"],
  outfile: "dist/index.cjs",
  bundle: true,
  sourcemap: true,
  format: "cjs",
  target: ["esnext"],
  platform: "neutral",
  jsx: "automatic",
  logLevel: "info",
  external: ["react", "react-dom", "lucide-react"],
});
